name: slim_sense
description: "A modern AI-powered weight loss application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^6.1.5
  flutter_facebook_auth: ^6.0.4
  cupertino_icons: ^1.0.8

  # State Management
  flutter_bloc: ^8.1.4
  provider: ^6.1.2
  equatable: ^2.0.5

  # Firebase
  firebase_core: ^2.29.0
  firebase_auth: ^4.17.9
  cloud_firestore: ^4.15.9
  firebase_storage: ^11.6.10
  firebase_crashlytics: ^3.4.18

  # Networking
  dio: ^5.4.2
  http: ^1.2.1
  connectivity_plus: ^6.0.1

  # Local Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  sqflite: ^2.3.2

  # UI Components
  flutter_svg: ^2.0.11
  cached_network_image: ^3.3.1
  table_calendar: ^3.0.9
  fl_chart: ^0.71.0
  percent_indicator: ^4.2.3
  lottie: ^3.1.0
  shimmer: ^3.0.0
  font_awesome_flutter: ^10.7.0

  # Utilities
  intl: ^0.19.0
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  url_launcher: ^6.2.5
  permission_handler: ^11.3.0
  barcode_scan2: ^4.3.0
  uuid: ^4.3.3
  logger: ^2.0.2+1
  flutter_dotenv: ^5.1.0

  # Payment
  in_app_purchase: ^3.1.13

  # Localization
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.7.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.4
  bloc_test: ^9.1.5
  build_runner: ^2.4.8
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - .env

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
